// actions constants
export const CART_PRODUCT_AMOUNT_ADD = "PRODUCT_AMOUNT_ADD";
export const CART_PRODUCT_AMOUNT_SUB = "PRODUCT_AMOUNT_SUB";
export const CART_SUBTOTAL_CALC = "CART_SUBTOTAL_CALC";
export const CART_TOTAL_CALC = "CART_TOTAL_CALC";
export const CART_SHIPPING_CALC = "CART_SHIPPING_CALC";
export const CART_COUPON_ADD = "CART_COUPON_ADD";
export const CART_COUPON_SUB = "CART_COUPON_SUB";
export const CART_RESET = "CART_RESET";
